In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
import seaborn as sns 
df = sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df[47:52 ]

sepal_length  sepal_width  petal_length  petal_width     species
47           4.6          3.2           1.4          0.2      setosa
48           5.3          3.7           1.5          0.2      setosa
49           5.0          3.3           1.4          0.2      setosa
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor

In [4]:
x = df.iloc[: , :-1]
y = df.iloc[: , -1]


In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 101)

# SVM CLASSIFICATION

In [8]:
from sklearn import svm

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf' , random_state=1, C=30, gamma='auto')
classifier.fit(x_train, y_train)
classifier.score(x_test,y_test)

0.9777777777777777

# K CROSS VALIDATION

In [10]:
from sklearn.model_selection import cross_val_score

In [11]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'),x,y,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [12]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'),x,y,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [13]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'),x,y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

### same thing using a loop

In [14]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
  for cval in C:
    cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval, gamma='auto'),x,y,cv=5)
    avg_scores[kval+'_'+str(cval)]=np.average(cv_scores)
avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

# GRID SEARCH

In [17]:
from sklearn.model_selection import  GridSearchCV
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 20]}
svc = svm.SVC()



In [18]:
clf = GridSearchCV(svc, parameters)


In [21]:
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 20], 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [22]:
print(clf.best_params_)

{'C': 1, 'kernel': 'linear'}


done bro
